### ISSUE TITLE
Can you please provide the dataset, and chest_label.zip is empty please provide a valid zip file.

### ISSUE THREAD

**Issue by swetharethinavel** [MIRACLE-Center/YOLO_Universal_Anatomical_Landmark_Detection#16]

**Comment by heqin-zhu** [comment]
The `chest_label.zip` is not empty and it's link is [YOLO_Universal_Anatomical_Landmark_Detection/data/chest_labels.zip](https://github.com/MIRACLE-Center/YOLO_Universal_Anatomical_Landmark_Detection/tree/main/data/chest_labels.zip). The GitHub webpage won't display it since it's a zip file. You can `git clone` or `download` this repo and fetch it through above path.

**Comment by swetharethinavel** [comment]
i have downloaded it and also gitcloned but still ,it is showing as empty file
